{{- if .Values.database_deploy.deploy -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-data
  name: database-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.database_deploy.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
{{- end -}}
