{{- if .Values.database_deploy.deploy -}}
---
apiVersion: apps/v1
# TODO statefulset, and configure replicas
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/fridgebot-fridgebot-network: "true"
        io.kompose.service: database
      namespace: {{ .Values.namespace }}
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: fridgebot-data
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
            {{- range $val := .Values.database_deploy.extraEnv }}
            - {{ $val }}
            {{- end }}
          image: {{ .Values.database_deploy.image }}
          name: database
          ports:
            - containerPort: 5432
          resources: {}
          imagePullPolicy: {{ .Values.database_deploy.pullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-data
      restartPolicy: Always
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database-data
status: {}
{{- end -}}
